"""add master district

Revision ID: 12dac44ec99b
Revises: 70105aff129f
Create Date: 2026-08-16 00:26:15.222205

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12dac44ec99b"
down_revision: Union[str, Sequence[str], None] = "70105aff129f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "masters", sa.Column("district", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("masters", "district")
    # ### end Alembic commands ###
