"""add master location

Revision ID: 70105aff129f
Revises: a4e8fe2cefcc
Create Date: 2026-08-16 00:11:50.229543

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70105aff129f'
down_revision: Union[str, Sequence[str], None] = 'a4e8fe2cefcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('masters', sa.Column('address', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('masters', 'address')
    op.drop_column('masters', 'city')
    # ### end Alembic commands ###
