"""add master location references

Revision ID: 9ff73e7a05ef
Revises: a11f45894d61
Create Date: 2026-08-16 18:48:35.162809

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ff73e7a05ef'
down_revision: Union[str, Sequence[str], None] = 'a11f45894d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('masters', sa.Column('city_id', sa.UUID(), nullable=True))
    op.add_column('masters', sa.Column('district_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_masters_city_id'), 'masters', ['city_id'], unique=False)
    op.create_index(op.f('ix_masters_district_id'), 'masters', ['district_id'], unique=False)
    op.create_foreign_key(None, 'masters', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'masters', 'districts', ['district_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(
        "masters_district_id_fkey",
        "masters",
        type_="foreignkey",
    )

    op.drop_constraint(
        "masters_city_id_fkey",
        "masters",
        type_="foreignkey",
    )

    op.drop_index(
        op.f("ix_masters_district_id"),
        table_name="masters",
    )

    op.drop_index(
        op.f("ix_masters_city_id"),
        table_name="masters",
    )

    op.drop_column(
        "masters",
        "district_id",
    )

    op.drop_column(
        "masters",
        "city_id",
    )
